### ISSUE TITLE
Doc keyword ignores newlines when generating documentation

### ISSUE THREAD

**Issue by mivanek** [Stankec/Rocket_Docs#1]
Hi,
When adding newlines under the DOC keyword, the generated documentation ignores newlines and keeps the documentation on one line.

The documentation comments look like this:
![Comments](https://www.dropbox.com/s/rphmgr9l7ov3a51/Screenshot%202015-03-10%2013.39.42.png)

And the generated docs look like this:
![Generated docs](https://www.dropbox.com/s/2cw8rgqmmkdk23i/Screenshot%202015-03-10%2013.41.32.png)

**Comment by Stankec** [comment]
Hi there!

I agree that that would look nicer and I have implemented the changes in the newest version of the gem.
The parser now doesn't omit newlines anymore. But it still ignores empty lines so it still isn't possible to insert a blank line in the middle of the DOC block.

Also, please not that the gem has been renamed to `rocket_docs`, you will have to change that in the `gemfile` and in the `routes.rb` file change `Interdasting` to `RocketDocs`.

Please report if something isn't to your liking :)

**Comment by mivanek** [comment]
Thanks, looking forward to having empty lines in docs once you get to it. :)
