### ISSUE TITLE
Cannot start server after adding gem to project

### ISSUE THREAD

**Issue by petarcurkovic** [Stankec/Rocket_Docs#2]
Hi,
After adding this gem to project, I can't start the server.

I'm getting this warning message:

warning: already initialized constant APP_PATH

![screen shot 2015-03-16 at 15 10 12](https://cloud.githubusercontent.com/assets/10612221/6669329/94cf98d0-cbf8-11e4-835a-fddffb7e8d9d.png)

Thanks!

**Comment by Stankec** [comment]
Hi there!

I think this isn't the gems fault but springs.
Here is a link to the issue on spring's repository https://github.com/rails/spring/issues/259

Hope this helps :)

**Comment by Stankec** [comment]
turns out this actually was my fault.
I required a development dependency in production code.
This is now fixed in the new version (0.0.3)

**Comment by petarcurkovic** [comment]
Yes, it work now! Thanks!

Regards
