### ISSUE TITLE
Bug with dropdowns on generated docs

### ISSUE THREAD

**Issue by petarcurkovic** [Stankec/Rocket_Docs#4]
Hi there!
It's me again :)

When the action has 2 or more underscores in name I cannot expand description of action in generated docs.

**Comment by Stankec** [comment]
Hi again!
Yes I noticed this my self.
Just fixed it. Please check if it works in the new version (0.0.4)

**Comment by petarcurkovic** [comment]
Hey, it work just fine right now!
Thanks again!
