### ISSUE TITLE
Add heading with name of API

### ISSUE THREAD

**Issue by petarcurkovic** [Stankec/Rocket_Docs#5]
Maybe you should put a name and description of API in header on api-doc page...

**Comment by Stankec** [comment]
Do you want this to be customizable?

**Comment by petarcurkovic** [comment]
It would be great!

**Comment by Stankec** [comment]
Hi! It's been a while.
I finally have something to show.
![screen shot 2015-03-24 at 22 27 15](https://cloud.githubusercontent.com/assets/1655218/6813357/07c46050-d275-11e4-96d8-473c41d09357.png)
Which can be done like this
![screen shot 2015-03-24 at 22 29 21](https://cloud.githubusercontent.com/assets/1655218/6813407/46dfcc48-d275-11e4-8a4d-e5a78249a575.png)

So this would be the name / title editing part of your request, but I don't quite get the description editing part. Could you perhaps better explane what you ment?

**Comment by petarcurkovic** [comment]
Hi!
It's OK now. Description of API can be something like this:

![screen shot 2015-03-25 at 08 36 45](https://cloud.githubusercontent.com/assets/10612221/6819962/2d17673a-d2ca-11e4-9ba8-ea6d6b35afde.png)

And its can be defined like title of API:
docs.description = 'My description of API...'

**Comment by Stankec** [comment]
Slept about this...
I like the description but I think that it will get messy really quick.
So not to make your `routes.rb` mess I decited to add an initializer method.

So now you can eather do this:
![screen shot 2015-03-25 at 09 20 47](https://cloud.githubusercontent.com/assets/1655218/6820556/d9fa8a9e-d2d0-11e4-890b-e8fe282d036e.png)

Or you can create a `config/initializers/rocket_docs.rb` and do this:
![screen shot 2015-03-25 at 09 22 44](https://cloud.githubusercontent.com/assets/1655218/6820599/f71414c4-d2d0-11e4-99e8-2b660627f374.png)

Think this will be much more useful if you have a large description.

As I will be occupied most of the day this will be pushed tomorrow :)

**Comment by petarcurkovic** [comment]
OK, great!
Thanks!

**Comment by Stankec** [comment]
The lecture which I have to attend to is quite boring so I decided to finish this up today.
Version 0.0.8 is out and the [documentation has been updated](https://github.com/Stankec/Rocket_Docs#configuration) to explain how to use the new functionality.

Please report back if this is to your liking :)

**Comment by petarcurkovic** [comment]
It's great now!
Thank you!
