### ISSUE TITLE
Description always visible

### ISSUE THREAD

**Issue by d4be4st** [Stankec/Rocket_Docs#7]
This is up for discusion

I think i would prefer that to be always visible

**Comment by Stankec** [comment]
Hi!
This kind of makes sense to me so I added `always_display_description` configuration option.
You would use it like this:

```Ruby
RocketDocs.config do |docs|
  docs.title = 'My Project'
  docs.description = 'This is my project'
  docs.always_display_description = true
end
```

This will also be released with 0.0.13
